version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bacancy
      MYSQL_USER: bacancy
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - "/home/bacancy/Desktop/Bacancy/internship_bacancy/tools And technologies/nomad/mysql job example/postgres-init:/docker-entrypoint-initdb.d"

