// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobListingInput struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Company     string           `json:"company"`
	URL         string           `json:"url"`
	JobProfile  *JobProfileInput `json:"jobProfile"`
	Technology  *TechnologyInput `json:"technology"`
}

type DeleteJobResponse struct {
	DeletedJobID string `json:"deletedJobId"`
}

type JobListing struct {
	ID          string      `json:"_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Company     string      `json:"company"`
	URL         *string     `json:"url,omitempty"`
	JobProfile  *JobProfile `json:"jobProfile"`
	Technology  *Technology `json:"technology"`
}

type JobProfile struct {
	ID                  string `json:"_id"`
	Title               string `json:"title"`
	Description         string `json:"description"`
	MinSalary           *int   `json:"min_salary,omitempty"`
	MaxSalary           *int   `json:"max_salary,omitempty"`
	Requirements        *int   `json:"requirements,omitempty"`
	JoinBy              string `json:"joinBy"`
	StrictProfilePolicy bool   `json:"strictProfilePolicy"`
}

type JobProfileInput struct {
	Title               string `json:"title"`
	Description         string `json:"description"`
	MinSalary           *int   `json:"min_salary,omitempty"`
	MaxSalary           *int   `json:"max_salary,omitempty"`
	Requirements        *int   `json:"requirements,omitempty"`
	JoinBy              string `json:"joinBy"`
	StrictProfilePolicy bool   `json:"strictProfilePolicy"`
}

type Mutation struct {
}

type Query struct {
}

type Technology struct {
	ID   string `json:"_id"`
	Name string `json:"name"`
}

type TechnologyInput struct {
	ID   *string `json:"_id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type UpdateJobListingInput struct {
	Title       *string          `json:"title,omitempty"`
	Description *string          `json:"description,omitempty"`
	URL         *string          `json:"url,omitempty"`
	JobProfile  *JobProfileInput `json:"jobProfile,omitempty"`
}
