version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: bacancy  # Replace 'mydatabase' with your desired database name
      POSTGRES_USER: bacancy    # Replace 'myuser' with your desired username
      POSTGRES_PASSWORD: admin  # Replace 'mypassword' with your desired password
    ports:
      - "5432:5432"  # Expose PostgreSQL default port
    command: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql